### ISSUE TITLE
I can't launch the webui

### ISSUE THREAD

**Issue by KenZXO** [etherealxx/volatile-concentration-localux-colab#10]
![Screenshot_2023-06-20-13-21-29-08_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/etherealxx/volatile-concentration-localux-colab/assets/137147224/14fe9c5d-d500-42c8-8980-111be24cf669)

**Comment by etherealxx** [comment]
@KenZXO Hi👋

Idk if you already figured this out or not, but make sure to use the latest version, the July 7 version: https://colab.research.google.com/github/etherealxx/volatile-concentration-localux-colab/blob/main/volatile_concentration_localux_colab.ipynb

If you the UI with big orange button doesn't show, you can check this guide: https://github.com/etherealxx/volatile-concentration-localux-colab/blob/main/error403guide.md

If you found another bug, you can open a new issue. Have a great day✨
