### ISSUE TITLE
Error 403

### ISSUE THREAD

**Issue by nbalive2k** [etherealxx/volatile-concentration-localux-colab#12]
It was working perfectly until yesterday
The yellow button doesn't appear anymore

"403. That’s an error.

That’s all we know."

**Comment by etherealxx** [comment]
@nbalive2k Hi👋

So i wrote this guide just now: https://github.com/etherealxx/volatile-concentration-localux-colab/blob/main/error403guide.md

try it, and tell me if it fixes everything😁

**Comment by nbalive2k** [comment]
Worked!
Thank you so much
