### ISSUE TITLE
ImportError: cannot import name '_compare_version' from 'torchmetrics.utilities.imports' (lite branch)

### ISSUE THREAD

**Issue by Indras91** [etherealxx/volatile-concentration-localux-colab#13]
Got an error today like this:

Model dosmix was chosen. It'll be downloaded soon. Continue scroll down and wait for the webui to be loaded.

Closing server running on port: 7861
Gathering aria2c code from /content/camendurus/lite/dosmix_webui_colab.ipynb...

26 packages can be upgraded. Run 'apt list --upgradable' to see them.
--2023-07-06 04:40:47--  http://launchpadlibrarian.net/367274644/libgoogle-perftools-dev_2.5-2.2ubuntu3_amd64.deb
Resolving launchpadlibrarian.net (launchpadlibrarian.net)... 185.125.189.229, 185.125.189.228, 2620:2d:4000:1001::8008, ...
Connecting to launchpadlibrarian.net (launchpadlibrarian.net)|185.125.189.229|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 203696 (199K) [application/x-debian-package]
Saving to: ‘libgoogle-perftools-dev_2.5-2.2ubuntu3_amd64.deb’

libgoogle-perftools 100%[===================>] 198.92K   404KB/s    in 0.5s    

2023-07-06 04:40:48 (404 KB/s) - ‘libgoogle-perftools-dev_2.5-2.2ubuntu3_amd64.deb’ saved [203696/203696]

--2023-07-06 04:40:48--  https://launchpad.net/ubuntu/+source/google-perftools/2.5-2.2ubuntu3/+build/14795286/+files/google-perftools_2.5-2.2ubuntu3_all.deb
Resolving launchpad.net (launchpad.net)... 185.125.189.222, 185.125.189.223, 2620:2d:4000:1001::8003, ...
Connecting to launchpad.net (launchpad.net)|185.125.189.222|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://launchpadlibrarian.net/367274642/google-perftools_2.5-2.2ubuntu3_all.deb [following]
--2023-07-06 04:40:48--  https://launchpadlibrarian.net/367274642/google-perftools_2.5-2.2ubuntu3_all.deb
Resolving launchpadlibrarian.net (launchpadlibrarian.net)... 185.125.189.229, 185.125.189.228, 2620:2d:4000:1001::8008, ...
Connecting to launchpadlibrarian.net (launchpadlibrarian.net)|185.125.189.229|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 294224 (287K) [application/x-debian-package]
Saving to: ‘google-perftools_2.5-2.2ubuntu3_all.deb’

google-perftools_2. 100%[===================>] 287.33K   515KB/s    in 0.6s    

2023-07-06 04:40:50 (515 KB/s) - ‘google-perftools_2.5-2.2ubuntu3_all.deb’ saved [294224/294224]

--2023-07-06 04:40:50--  https://launchpad.net/ubuntu/+source/google-perftools/2.5-2.2ubuntu3/+build/14795286/+files/libtcmalloc-minimal4_2.5-2.2ubuntu3_amd64.deb
Resolving launchpad.net (launchpad.net)... 185.125.189.222, 185.125.189.223, 2620:2d:4000:1001::8003, ...
Connecting to launchpad.net (launchpad.net)|185.125.189.222|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://launchpadlibrarian.net/367274648/libtcmalloc-minimal4_2.5-2.2ubuntu3_amd64.deb [following]
--2023-07-06 04:40:50--  https://launchpadlibrarian.net/367274648/libtcmalloc-minimal4_2.5-2.2ubuntu3_amd64.deb
Resolving launchpadlibrarian.net (launchpadlibrarian.net)... 185.125.189.229, 185.125.189.228, 2620:2d:4000:1001::8008, ...
Connecting to launchpadlibrarian.net (launchpadlibrarian.net)|185.125.189.229|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 91644 (89K) [application/x-debian-package]
Saving to: ‘libtcmalloc-minimal4_2.5-2.2ubuntu3_amd64.deb’

libtcmalloc-minimal 100%[===================>]  89.50K   302KB/s    in 0.3s    

2023-07-06 04:40:51 (302 KB/s) - ‘libtcmalloc-minimal4_2.5-2.2ubuntu3_amd64.deb’ saved [91644/91644]

--2023-07-06 04:40:51--  https://launchpad.net/ubuntu/+source/google-perftools/2.5-2.2ubuntu3/+build/14795286/+files/libgoogle-perftools4_2.5-2.2ubuntu3_amd64.deb
Resolving launchpad.net (launchpad.net)... 185.125.189.222, 185.125.189.223, 2620:2d:4000:1001::8003, ...
Connecting to launchpad.net (launchpad.net)|185.125.189.222|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://launchpadlibrarian.net/367274647/libgoogle-perftools4_2.5-2.2ubuntu3_amd64.deb [following]
--2023-07-06 04:40:52--  https://launchpadlibrarian.net/367274647/libgoogle-perftools4_2.5-2.2ubuntu3_amd64.deb
Resolving launchpadlibrarian.net (launchpadlibrarian.net)... 185.125.189.229, 185.125.189.228, 2620:2d:4000:1001::8008, ...
Connecting to launchpadlibrarian.net (launchpadlibrarian.net)|185.125.189.229|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 189628 (185K) [application/x-debian-package]
Saving to: ‘libgoogle-perftools4_2.5-2.2ubuntu3_amd64.deb’

libgoogle-perftools 100%[===================>] 185.18K   367KB/s    in 0.5s    

2023-07-06 04:40:53 (367 KB/s) - ‘libgoogle-perftools4_2.5-2.2ubuntu3_amd64.deb’ saved [189628/189628]

The following NEW packages will be installed:
  libunwind-dev
0 upgraded, 1 newly installed, 0 to remove and 26 not upgraded.
Need to get 472 kB of archives.
After this operation, 4,164 kB of additional disk space will be used.
Selecting previously unselected package libunwind-dev:amd64.
(Reading database ... 123071 files and directories currently installed.)
Preparing to unpack .../libunwind-dev_1.2.1-9ubuntu0.1_amd64.deb ...
Unpacking libunwind-dev:amd64 (1.2.1-9ubuntu0.1) ...
Setting up libunwind-dev:amd64 (1.2.1-9ubuntu0.1) ...
Processing triggers for man-db (2.9.1-1) ...
dpkg: warning: downgrading google-perftools from 2.7-1ubuntu2 to 2.5-2.2ubuntu3
(Reading database ... 123124 files and directories currently installed.)
Preparing to unpack google-perftools_2.5-2.2ubuntu3_all.deb ...
Unpacking google-perftools (2.5-2.2ubuntu3) over (2.7-1ubuntu2) ...
dpkg: warning: downgrading libgoogle-perftools4:amd64 from 2.7-1ubuntu2 to 2.5-2.2ubuntu3
Preparing to unpack libgoogle-perftools4_2.5-2.2ubuntu3_amd64.deb ...
Unpacking libgoogle-perftools4 (2.5-2.2ubuntu3) over (2.7-1ubuntu2) ...
Selecting previously unselected package libgoogle-perftools-dev.
Preparing to unpack libgoogle-perftools-dev_2.5-2.2ubuntu3_amd64.deb ...
Unpacking libgoogle-perftools-dev (2.5-2.2ubuntu3) ...
dpkg: warning: downgrading libtcmalloc-minimal4:amd64 from 2.7-1ubuntu2 to 2.5-2.2ubuntu3
Preparing to unpack libtcmalloc-minimal4_2.5-2.2ubuntu3_amd64.deb ...
Unpacking libtcmalloc-minimal4 (2.5-2.2ubuntu3) over (2.7-1ubuntu2) ...
Setting up libtcmalloc-minimal4 (2.5-2.2ubuntu3) ...
Setting up libgoogle-perftools4 (2.5-2.2ubuntu3) ...
Setting up libgoogle-perftools-dev (2.5-2.2ubuntu3) ...
Setting up google-perftools (2.5-2.2ubuntu3) ...
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for libc-bin (2.31-0ubuntu9.9) ...
env: LD_PRELOAD=libtcmalloc.so
Gathering code from /content/camendurus/lite/dosmix_webui_colab.ipynb...

apt -y install -qq aria2 libcairo2-dev pkg-config python3-dev

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

pkg-config is already the newest version (0.29.1-0ubuntu4).
python3-dev is already the newest version (3.8.2-0ubuntu2).
python3-dev set to manually installed.
The following additional packages will be installed:
  libaria2-0 libblkid-dev libblkid1 libc-ares2 libcairo-script-interpreter2
  libffi-dev libglib2.0-dev libglib2.0-dev-bin liblzo2-2 libmount-dev
  libmount1 libpixman-1-dev libselinux1-dev libsepol1-dev libxcb-render0-dev
  libxcb-shm0-dev
Suggested packages:
  libcairo2-doc libgirepository1.0-dev libglib2.0-doc libgdk-pixbuf2.0-bin
  | libgdk-pixbuf2.0-dev libxml2-utils
The following NEW packages will be installed:
  aria2 libaria2-0 libblkid-dev libc-ares2 libcairo-script-interpreter2
  libcairo2-dev libffi-dev libglib2.0-dev libglib2.0-dev-bin liblzo2-2
  libmount-dev libpixman-1-dev libselinux1-dev libsepol1-dev
  libxcb-render0-dev libxcb-shm0-dev
The following packages will be upgraded:
  libblkid1 libmount1
2 upgraded, 16 newly installed, 0 to remove and 28 not upgraded.
Need to get 5,254 kB of archives.
After this operation, 25.9 MB of additional disk space will be used.
(Reading database ... 
(Reading database ... 100%(Reading database ... 123215 files and directories currently installed.)
Preparing to unpack .../libblkid1_2.34-0.1ubuntu9.4_amd64.deb ...
Unpacking libblkid1:amd64 (2.34-0.1ubuntu9.4) over (2.34-0.1ubuntu9.3) ...
Setting up libblkid1:amd64 (2.34-0.1ubuntu9.4) ...
(Reading database ... 
(Reading database ... 100%(Reading database ... 123215 files and directories currently installed.)
Preparing to unpack .../libmount1_2.34-0.1ubuntu9.4_amd64.deb ...
Unpacking libmount1:amd64 (2.34-0.1ubuntu9.4) over (2.34-0.1ubuntu9.3) ...
Setting up libmount1:amd64 (2.34-0.1ubuntu9.4) ...
Selecting previously unselected package libc-ares2:amd64.
(Reading database ... 
(Reading database ... 100%(Reading database ... 123215 files and directories currently installed.)
Preparing to unpack .../00-libc-ares2_1.15.0-1ubuntu0.3_amd64.deb ...
Unpacking libc-ares2:amd64 (1.15.0-1ubuntu0.3) ...
Selecting previously unselected package libaria2-0:amd64.
Preparing to unpack .../01-libaria2-0_1.35.0-1build1_amd64.deb ...
Unpacking libaria2-0:amd64 (1.35.0-1build1) ...
Selecting previously unselected package aria2.
Preparing to unpack .../02-aria2_1.35.0-1build1_amd64.deb ...
Unpacking aria2 (1.35.0-1build1) ...
Selecting previously unselected package liblzo2-2:amd64.
Preparing to unpack .../03-liblzo2-2_2.10-2_amd64.deb ...
Unpacking liblzo2-2:amd64 (2.10-2) ...
Selecting previously unselected package libcairo-script-interpreter2:amd64.
Preparing to unpack .../04-libcairo-script-interpreter2_1.16.0-4ubuntu1_amd64.deb ...
Unpacking libcairo-script-interpreter2:amd64 (1.16.0-4ubuntu1) ...
Selecting previously unselected package libpixman-1-dev:amd64.
Preparing to unpack .../05-libpixman-1-dev_0.38.4-0ubuntu2.1_amd64.deb ...
Unpacking libpixman-1-dev:amd64 (0.38.4-0ubuntu2.1) ...
Selecting previously unselected package libxcb-render0-dev:amd64.
Preparing to unpack .../06-libxcb-render0-dev_1.14-2_amd64.deb ...
Unpacking libxcb-render0-dev:amd64 (1.14-2) ...
Selecting previously unselected package libxcb-shm0-dev:amd64.
Preparing to unpack .../07-libxcb-shm0-dev_1.14-2_amd64.deb ...
Unpacking libxcb-shm0-dev:amd64 (1.14-2) ...
Selecting previously unselected package libffi-dev:amd64.
Preparing to unpack .../08-libffi-dev_3.3-4_amd64.deb ...
Unpacking libffi-dev:amd64 (3.3-4) ...
Selecting previously unselected package libglib2.0-dev-bin.
Preparing to unpack .../09-libglib2.0-dev-bin_2.64.6-1~ubuntu20.04.6_amd64.deb ...
Unpacking libglib2.0-dev-bin (2.64.6-1~ubuntu20.04.6) ...
Selecting previously unselected package libblkid-dev:amd64.
Preparing to unpack .../10-libblkid-dev_2.34-0.1ubuntu9.4_amd64.deb ...
Unpacking libblkid-dev:amd64 (2.34-0.1ubuntu9.4) ...
Selecting previously unselected package libmount-dev:amd64.
Preparing to unpack .../11-libmount-dev_2.34-0.1ubuntu9.4_amd64.deb ...
Unpacking libmount-dev:amd64 (2.34-0.1ubuntu9.4) ...
Selecting previously unselected package libsepol1-dev:amd64.
Preparing to unpack .../12-libsepol1-dev_3.0-1ubuntu0.1_amd64.deb ...
Unpacking libsepol1-dev:amd64 (3.0-1ubuntu0.1) ...
Selecting previously unselected package libselinux1-dev:amd64.
Preparing to unpack .../13-libselinux1-dev_3.0-1build2_amd64.deb ...
Unpacking libselinux1-dev:amd64 (3.0-1build2) ...
Selecting previously unselected package libglib2.0-dev:amd64.
Preparing to unpack .../14-libglib2.0-dev_2.64.6-1~ubuntu20.04.6_amd64.deb ...
Unpacking libglib2.0-dev:amd64 (2.64.6-1~ubuntu20.04.6) ...
Selecting previously unselected package libcairo2-dev:amd64.
Preparing to unpack .../15-libcairo2-dev_1.16.0-4ubuntu1_amd64.deb ...
Unpacking libcairo2-dev:amd64 (1.16.0-4ubuntu1) ...
Setting up libglib2.0-dev-bin (2.64.6-1~ubuntu20.04.6) ...
Setting up libblkid-dev:amd64 (2.34-0.1ubuntu9.4) ...
Setting up libpixman-1-dev:amd64 (0.38.4-0ubuntu2.1) ...
Setting up libsepol1-dev:amd64 (3.0-1ubuntu0.1) ...
Setting up liblzo2-2:amd64 (2.10-2) ...
Setting up libc-ares2:amd64 (1.15.0-1ubuntu0.3) ...
Setting up libffi-dev:amd64 (3.3-4) ...
Setting up libxcb-shm0-dev:amd64 (1.14-2) ...
Setting up libxcb-render0-dev:amd64 (1.14-2) ...
Setting up libmount-dev:amd64 (2.34-0.1ubuntu9.4) ...
Setting up libcairo-script-interpreter2:amd64 (1.16.0-4ubuntu1) ...
Setting up libaria2-0:amd64 (1.35.0-1build1) ...
Setting up libselinux1-dev:amd64 (3.0-1build2) ...
Setting up aria2 (1.35.0-1build1) ...
Setting up libglib2.0-dev:amd64 (2.64.6-1~ubuntu20.04.6) ...
Processing triggers for libglib2.0-0:amd64 (2.64.6-1~ubuntu20.04.6) ...
Processing triggers for libc-bin (2.31-0ubuntu9.9) ...
Processing triggers for man-db (2.9.1-1) ...
Setting up libcairo2-dev:amd64 (1.16.0-4ubuntu1) ...
pip install -q torch==1.13.1+cu116 torchvision==0.14.1+cu116 torchaudio==0.13.1 torchtext==0.14.1 torchdata==0.5.1 --extra-index-url https://download.pytorch.org/whl/cu116 -U

tcmalloc: large alloc 1977917440 bytes == 0x2550000 @  0x7f27bc55f1e7 0x5f1808 0x62834d 0x6847bc 0x565a08 0x565a9f 0x53f5ae 0x5a8d85 0x628b20 0x5a8d85 0x628b20 0x5a8d85 0x628b20 0x5a8d85 0x628b20 0x5a8d85 0x628b20 0x5a8d85 0x628b20 0x5a8d85 0x628b20 0x5a9a35 0x628b20 0x5a8d85 0x628b20 0x5a8d85 0x5a7951 0x54890a 0x539519 0x6a0a66 0x5ad363
tcmalloc: large alloc 2472402944 bytes == 0x7839a000 @  0x7f27bc560615 0x628262 0x6847bc 0x565a08 0x565a9f 0x53f5ae 0x5a8d85 0x628b20 0x5a8d85 0x628b20 0x5a8d85 0x628b20 0x5a8d85 0x628b20 0x5a8d85 0x628b20 0x5a8d85 0x628b20 0x5a8d85 0x628b20 0x5a9a35 0x628b20 0x5a8d85 0x628b20 0x5a8d85 0x5a7951 0x54890a 0x539519 0x6a0a66 0x5ad363 0x5484aa
tcmalloc: large alloc 1977917440 bytes == 0x2550000 @  0x7f27bc55f1e7 0x62e02b 0x62cdf0 0x53f5ae 0x5a8d85 0x628b20 0x5a8d85 0x628b20 0x5a8d85 0x5a7951 0x54890a 0x539519 0x6a0a66 0x5ad363 0x5484aa 0x5ad363 0x5484aa 0x5ad363 0x628b20 0x5a8d85 0x5484aa 0x5a9a35 0x53e48a 0x5a906b 0x53e48a 0x5a906b 0x53e48a 0x5a906b 0x628b20 0x62b659 0x62b78a
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 GB 866.6 kB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.2/24.2 MB 32.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 33.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 18.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.6/4.6 MB 52.3 MB/s eta 0:00:00
pip install -q xformers==0.0.16 triton==2.0.0 -U

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.9/50.9 MB 11.1 MB/s eta 0:00:00
git clone -b v2.1 https://github.com/camenduru/stable-diffusion-webui /content/volatile-concentration-localux

Cloning into '/content/volatile-concentration-localux'...
git clone https://huggingface.co/embed/negative /content/volatile-concentration-localux/embeddings/negative

Cloning into '/content/volatile-concentration-localux/embeddings/negative'...
git clone https://huggingface.co/embed/lora /content/volatile-concentration-localux/models/Lora/positive

Cloning into '/content/volatile-concentration-localux/models/Lora/positive'...
Filtering content: 100% (3/3), 239.93 MiB | 98.39 MiB/s, done.aria2c --console-log-level=error -c -x 16 -s 16 -k 1M https://huggingface.co/embed/upscale/resolve/main/4x-UltraSharp.pth -d /content/volatile-concentration-localux/models/ESRGAN -o 4x-UltraSharp.pth

[#92d368 17MiB/63MiB(26%) CN:16 DL:89MiB]
Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
92d368|OK  |    66MiB/s|/content/volatile-concentration-localux/models/ESRGAN/4x-UltraSharp.pth

Status Legend:
(OK):download completed.
wget https://raw.githubusercontent.com/camenduru/stable-diffusion-webui-scripts/main/run_n_times.py -O /content/volatile-concentration-localux/scripts/run_n_times.py

--2023-07-06 04:44:04--  https://raw.githubusercontent.com/camenduru/stable-diffusion-webui-scripts/main/run_n_times.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.110.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 533 [text/plain]
Saving to: ‘/content/volatile-concentration-localux/scripts/run_n_times.py’

0K                                                       100% 43.5M=0s
2023-07-06 04:44:04 (43.5 MB/s) - ‘/content/volatile-concentration-localux/scripts/run_n_times.py’ saved [533/533]

git clone -b v2.1 https://github.com/camenduru/deforum-for-automatic1111-webui /content/volatile-concentration-localux/extensions/deforum-for-automatic1111-webui

Cloning into '/content/volatile-concentration-localux/extensions/deforum-for-automatic1111-webui'...
git clone -b v2.1 https://github.com/camenduru/stable-diffusion-webui-images-browser /content/volatile-concentration-localux/extensions/stable-diffusion-webui-images-browser

Cloning into '/content/volatile-concentration-localux/extensions/stable-diffusion-webui-images-browser'...
git clone -b v2.1 https://github.com/camenduru/stable-diffusion-webui-huggingface /content/volatile-concentration-localux/extensions/stable-diffusion-webui-huggingface

Cloning into '/content/volatile-concentration-localux/extensions/stable-diffusion-webui-huggingface'...
git clone -b v2.1 https://github.com/camenduru/sd-civitai-browser /content/volatile-concentration-localux/extensions/sd-civitai-browser

Cloning into '/content/volatile-concentration-localux/extensions/sd-civitai-browser'...
git clone -b v2.1 https://github.com/camenduru/sd-webui-additional-networks /content/volatile-concentration-localux/extensions/sd-webui-additional-networks

Cloning into '/content/volatile-concentration-localux/extensions/sd-webui-additional-networks'...
git clone -b v2.1 https://github.com/camenduru/sd-webui-tunnels /content/volatile-concentration-localux/extensions/sd-webui-tunnels

Cloning into '/content/volatile-concentration-localux/extensions/sd-webui-tunnels'...
git clone -b v2.1 https://github.com/camenduru/batchlinks-webui /content/volatile-concentration-localux/extensions/batchlinks-webui

Cloning into '/content/volatile-concentration-localux/extensions/batchlinks-webui'...
git clone -b v2.1 https://github.com/camenduru/stable-diffusion-webui-catppuccin /content/volatile-concentration-localux/extensions/stable-diffusion-webui-catppuccin

Cloning into '/content/volatile-concentration-localux/extensions/stable-diffusion-webui-catppuccin'...
git clone -b v2.1 https://github.com/camenduru/a1111-sd-webui-locon /content/volatile-concentration-localux/extensions/a1111-sd-webui-locon

Cloning into '/content/volatile-concentration-localux/extensions/a1111-sd-webui-locon'...
git clone -b v2.1 https://github.com/camenduru/stable-diffusion-webui-rembg /content/volatile-concentration-localux/extensions/stable-diffusion-webui-rembg

Cloning into '/content/volatile-concentration-localux/extensions/stable-diffusion-webui-rembg'...
git clone -b v2.1 https://github.com/camenduru/stable-diffusion-webui-two-shot /content/volatile-concentration-localux/extensions/stable-diffusion-webui-two-shot

Cloning into '/content/volatile-concentration-localux/extensions/stable-diffusion-webui-two-shot'...
git clone -b v2.1 https://github.com/camenduru/sd-webui-aspect-ratio-helper /content/volatile-concentration-localux/extensions/sd-webui-aspect-ratio-helper

Cloning into '/content/volatile-concentration-localux/extensions/sd-webui-aspect-ratio-helper'...
git clone -b v2.1 https://github.com/camenduru/asymmetric-tiling-sd-webui /content/volatile-concentration-localux/extensions/asymmetric-tiling-sd-webui

Cloning into '/content/volatile-concentration-localux/extensions/asymmetric-tiling-sd-webui'...
git reset --hard

HEAD is now at a9fed7c3 Merge pull request #8503 from mcmonkey4eva/filename-length-limit-fix
git -C /content/volatile-concentration-localux/repositories/stable-diffusion-stability-ai reset --hard

fatal: cannot change to '/content/volatile-concentration-localux/repositories/stable-diffusion-stability-ai': No such file or directory
git clone https://github.com/a2569875/stable-diffusion-webui-composable-lora /content/volatile-concentration-localux/extensions/stable-diffusion-webui-composable-lora

Cloning into '/content/volatile-concentration-localux/extensions/stable-diffusion-webui-composable-lora'...
git clone https://github.com/DominikDoom/a1111-sd-webui-tagcomplete /content/volatile-concentration-localux/extensions/a1111-sd-webui-tagcomplete

Cloning into '/content/volatile-concentration-localux/extensions/a1111-sd-webui-tagcomplete'...
aria2c --console-log-level=error -c -x 16 -s 16 -k 1M https://huggingface.co/ckpt/dosmix/resolve/main/dosmix_.safetensors -d /content/volatile-concentration-localux/models/Stable-diffusion -o dosmix_.safetensors

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
9c18a5|OK  |   234MiB/s|/content/volatile-concentration-localux/models/Stable-diffusion/dosmix_.safetensors

Status Legend:
(OK):download completed.
aria2c --console-log-level=error -c -x 16 -s 16 -k 1M https://huggingface.co/ckpt/sd-vae-ft-mse-original/resolve/main/vae-ft-mse-840000-ema-pruned.ckpt -d /content/volatile-concentration-localux/models/Stable-diffusion -o dosmix_.vae.pt

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
73e7e0|OK  |   184MiB/s|/content/volatile-concentration-localux/models/Stable-diffusion/dosmix_.vae.pt

Status Legend:
(OK):download completed.
/content/volatile-concentration-localux
launching the webui...

Python 3.10.12 (main, Jun  7 2023, 12:45:35) [GCC 9.4.0]
Commit hash: a9fed7c364061ae6efb37f797b6b522cb3cf7aa2
Installing gfpgan
Installing clip
Installing open_clip
Cloning Stable Diffusion into /content/volatile-concentration-localux/repositories/stable-diffusion-stability-ai...
Cloning Taming Transformers into /content/volatile-concentration-localux/repositories/taming-transformers...
Cloning K-diffusion into /content/volatile-concentration-localux/repositories/k-diffusion...
Cloning CodeFormer into /content/volatile-concentration-localux/repositories/CodeFormer...
Cloning BLIP into /content/volatile-concentration-localux/repositories/BLIP...
Installing requirements for CodeFormer
Installing requirements for Web UI
Installing Deforum requirement: av
Installing Deforum requirement: pims

Installing rembg
Installing onnxruntime for REMBG extension
Installing pymatting for REMBG extension

Installing pycloudflared

Installing requirements for CivitAI Browser

Launching Web UI with arguments: --listen --xformers --enable-insecure-extension-access --theme dark --gradio-queue --multiple
2023-07-06 04:46:52.399155: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "/content/volatile-concentration-localux/launch.py", line 382, in <module>
    start()
  File "/content/volatile-concentration-localux/launch.py", line 372, in start
    import webui
  File "/content/volatile-concentration-localux/webui.py", line 28, in <module>
    from modules import extra_networks, ui_extra_networks_checkpoints
  File "/content/volatile-concentration-localux/modules/ui_extra_networks_checkpoints.py", line 5, in <module>
    from modules import shared, ui_extra_networks, sd_models
  File "/content/volatile-concentration-localux/modules/sd_models.py", line 17, in <module>
    from modules.sd_hijack_inpainting import do_inpainting_hijack
  File "/content/volatile-concentration-localux/modules/sd_hijack_inpainting.py", line 7, in <module>
    import ldm.models.diffusion.ddpm
  File "/content/volatile-concentration-localux/repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddpm.py", line 12, in <module>
    import pytorch_lightning as pl
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/__init__.py", line 34, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/callbacks/__init__.py", line 25, in <module>
    from pytorch_lightning.callbacks.progress import ProgressBarBase, RichProgressBar, TQDMProgressBar
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/callbacks/progress/__init__.py", line 22, in <module>
    from pytorch_lightning.callbacks.progress.rich_progress import RichProgressBar  # noqa: F401
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/callbacks/progress/rich_progress.py", line 20, in <module>
    from torchmetrics.utilities.imports import _compare_version
ImportError: cannot import name '_compare_version' from 'torchmetrics.utilities.imports' (/usr/local/lib/python3.10/dist-packages/torchmetrics/utilities/imports.py)

**Comment by etherealxx** [comment]
Hello👋

I'm using the same settings as you, opening dosmix, and it works just fine. Have you tried again? And make sure you're using the latest 2 July version.

https://colab.research.google.com/github/etherealxx/volatile-concentration-localux-colab/blob/main/volatile_concentration_localux_colab.ipynb

**Comment by Indras91** [comment]
Its happen on the lite version, the stable version work fine, but i dont like the stable version is im always got some infinite loading on some button, like chekpoint, vae, most case is on civitai browser extension is always happen,

**Comment by etherealxx** [comment]
Oh, my bad then. I just realized. My code is wrongly coded for the lite branch. That's why no extension is showing. I'll fix it asap.

**Comment by etherealxx** [comment]
update, it's not from my side, it's from torchmetrics updated to a newer version, and camenduru hasn't updated his code yet, and since this colab basically copies everything from camenduru's, i'll need to wait for him, or i could apply the fix earlier.

the issue and solution: https://github.com/camenduru/stable-diffusion-webui-colab/issues/451

**Comment by etherealxx** [comment]
@Indras91 Hi👋

Check out the newest July 7 version. It fixes all the problem, hopefully. Enjoy✨

**Comment by Indras91** [comment]
Ok, thanks for the hardwork,
