### ISSUE TITLE
I can't acces the webui either

### ISSUE THREAD

**Issue by Alassi0** [etherealxx/volatile-concentration-localux-colab#18]
![IMG_9367](https://github.com/etherealxx/volatile-concentration-localux-colab/assets/139177672/2d7bf0ec-3bb7-4e6a-baaa-b5ba1bd98b59)
I'm sure i'm using the last version of the collab, but still i have this error

**Comment by etherealxx** [comment]
Sorry, it was a three character typo from last night. Please try again and tell me if the problem is fixed🙏
![Screenshot_2023-07-11-06-39-48-574_org.bromite.bromite.jpg](https://github.com/etherealxx/volatile-concentration-localux-colab/assets/64251396/722d6d4d-0797-45db-8954-c94024f03a24)

**Comment by basedholychad** [comment]
thanks for adetailer extensions, super useful tools 😉😉😉

**Comment by Alassi0** [comment]
> Sorry, it was a three character typo from last night. Please try again and tell me if the problem is fixed🙏
> ![Screenshot_2023-07-11-06-39-48-574_org.bromite.bromite.jpg](https://user-images.githubusercontent.com/64251396/252514958-722d6d4d-0797-45db-8954-c94024f03a24.jpg)

Yes, now it works, ty so much
