### ISSUE TITLE
custom model

### ISSUE THREAD

**Issue by mgmmgm123** [etherealxx/volatile-concentration-localux-colab#2]
hi sir i have fork and modified the model repositorie of camenduru/stable-diffusion-webui-colab for personal use, I want to use my custom model repositorie instead of camenduru's, please tell me how to run it, thanks

**Comment by mgmmgm123** [comment]
@etherealxx check what??? that link not work with free colab now

**Comment by etherealxx** [comment]
> @etherealxx check what??? that link not work with free colab now

that link i shared to you, this one:
https://colab.research.google.com/github/mgmmgm123/test2/blob/main/stable/all_in_one_pixel_model_webui_colab.ipynb

i believe that is the `fork and modified the model repositorie of camenduru/stable-diffusion-webui-colab for personal use` you mentioned. if it isn't, then maybe i didn't understand your question properly

**Comment by unLomTrois** [comment]
@etherealxx I think the question is basically about to have an ability to provide your own custom notebook with preinstalled models, and run it from your colab, like, instead of using blank camenduru's, just git clone the notebook from the custom provided link and run all the staff

**Comment by seq2193** [comment]
Let me study the code carefully,
It is found that it is connected to camenduru to download the .ipynb file,
Can I use a custom ipynb file to use it?

**Comment by mgmmgm123** [comment]
@etherealxx yes, right

**Comment by basedholychad** [comment]
since the camen colab is dead (due to popular) you're my only hope now, thanks for making this colab, sorry i don't know where to message you lul, hope you don't abandon this project

**Comment by etherealxx** [comment]
@basedholychad aww thank you. I was able to figured out the error 404 problem that people experiencing, and with that i think i'll continue to maintain this project, i guess.

**Comment by etherealxx** [comment]
> yes, right, i want use custom ipynb file

@mgmmgm123 currently i'm busy with other stuff, but i'll try to add that feature, thanks for the feedback

**Comment by seq2193** [comment]
I asked chatgpt and it seems that other .ipynb files can be opened in colab, you can try it!


%cd /content/drive/MyDrive/Colab Notebooks/
%run 副本cetus_mix_v3_1_webui_colab.ipynb
