### ISSUE TITLE
Web Ui Stopping the Cell

### ISSUE THREAD

**Issue by Sunkybunky** [etherealxx/volatile-concentration-localux-colab#22]
I keep getting this error when trying to load web ui, every thing else downloads but when it gets to the web ui part it does this message "Launching Web UI with arguments: --ckpt /content/stable-diffusion-webui/models/Stable-diffusion/Anything-V3.0.safetensors --vae-path /content/stable-diffusion-webui/models/Stable-diffusion/Anything-V3.0.vae.pt --share --xformers --enable-insecure-extension-access --gradio-queue
src/tcmalloc.cc:283] Attempt to free invalid pointer 0x5b5a97409740" and it stops

**Comment by FxyDreamer** [comment]
web ui stopping the cell, I don't know if it will be related but i get this: "Launching Web UI with arguments: --listen --xformers --enable-insecure-extension-access --theme dark --gradio-queue --multiple
src/tcmalloc.cc:283] Attempt to free invalid pointer 0x5c79367a9740". On lite, stable or nightly

**Comment by deiver-romero** [comment]
Recent updates were pushed here: https://github.com/camenduru/stable-diffusion-webui-colab/tree/drive, you could use those colabs in the meantime.

**Comment by etherealxx** [comment]
@deiver-romero i updated mine too just like 15 minutes ago

try the newest version (july 20) and see if it works🙏
![image](https://github.com/etherealxx/volatile-concentration-localux-colab/assets/64251396/466ee7e8-6d8e-4628-b519-c741378721aa)

**Comment by kirin161** [comment]
Tried the new version. It is working (for the stable notebook). Thank you for the fix @etherealxx !!

**Comment by FxyDreamer** [comment]
the new version works perfect, thanks!

**Comment by etherealxx** [comment]
Your welcome guys😁
Feel free to submit another issue if a new bug or problem appears again in the future👍🎇
