### ISSUE TITLE
Colab error

### ISSUE THREAD

**Issue by eyetest42** [etherealxx/volatile-concentration-localux-colab#29]
> Traceback (most recent call last):
>   File "/content/volatile-concentration-localux/launch.py", line 39, in <module>
>     main()
>   File "/content/volatile-concentration-localux/launch.py", line 30, in main
>     os.system(f"""sed -i -e "s/dict()))/dict())).cuda()/g" /content/volatile-concentration-localux/repositories/stable-diffusion-stability-ai/ldm/util.py""")
> NameError: name 'os' is not defined

**Comment by basedholychad** [comment]
is this the end??@@
![Untitled](https://github.com/etherealxx/volatile-concentration-localux-colab/assets/126396858/1144a879-386f-4bbf-b993-dbcd0181b267)

**Comment by etherealxx** [comment]
@eyetest @basedholychad Hi guys👋
Please check the new version (27 July), i hope it fixes everything

**Comment by verydumbperson** [comment]
@etherealxx just wanna say i appreciate you for your work!
keep up the good work man❤️
