### ISSUE TITLE
Failed to launch WebUI

### ISSUE THREAD

**Issue by Itsappuru** [etherealxx/volatile-concentration-localux-colab#30]
Status Legend:
(OK):download completed.
/content/volatile-concentration-localux
launching the webui...

fatal: No names found, cannot describe anything.
Python 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0]
Version: ## 1.4.1
Commit hash: f865d3e11647dfd6c7b2cdf90dde24680e58acd8
Installing requirements

Traceback (most recent call last):
  File "/content/volatile-concentration-localux/launch.py", line 39, in <module>
    main()
  File "/content/volatile-concentration-localux/launch.py", line 30, in main
    os.system(f"""sed -i -e "s/dict()))/dict())).cuda()/g" /content/volatile-concentration-localux/repositories/stable-diffusion-stability-ai/ldm/util.py""")
NameError: name 'os' is not defined

**Comment by Itsappuru** [comment]
tried turning off Choose Models and still didn't work

**Comment by etherealxx** [comment]
@Itsappuru @FxyDreamer Hi guys👋
Please check the new version (27 July), i hope it fixes everything

camenduru updated his repo so i need to adjust my code.

**Comment by FxyDreamer** [comment]
yep works fine! ty!
