### ISSUE TITLE
Use drive storage

### ISSUE THREAD

**Issue by maozdemir** [etherealxx/volatile-concentration-localux-colab#9]
So, I have loads of models and LoRAs but it's almost impossible to access them without a Google Drive integration. maybe you could make it so that it'd be working similar to TheLastBen's colab?

**Comment by etherealxx** [comment]
![image](https://github.com/etherealxx/volatile-concentration-localux-colab/assets/64251396/e24655cd-043b-4935-bba7-b798120986f6)

You can always use this cell on the debug area to connect to your drive. Then you can use  python code to copy files from drive to the working directory, or use some extension that can also does that like batchlinks.

For full on drive support (the whole stable diffusion inside your drive), i'm not planning for that soon, but [camenduru has one](https://github.com/camenduru/stable-diffusion-webui-colab/tree/drive), colab pro only though.

Btw if you need any more question about copying the file with python, just reply to this issue. 

Have a good day✨

**Comment by maozdemir** [comment]
This is how I added.

```
(If you got 'Error 404' when the big orange button is supposed to shows up, visit here:)

from google.colab import drive
drive.mount('/content/drive')

#!cp -R /content/drive/MyDrive/path/to/models /content/volatile-concentration-localux/models

!mount --bind /content/drive/MyDrive/path/to/models /content/volatile-concentration-localux/models
!mount -o bind,remount,ro /content/volatile-concentration-localux/models


!python /content/vcltools/setuptimer.py
!echo -n {start_colab} > /content/volatile-concentration-localux/static/colabTimer.txt
!wget -q https://raw.githubusercontent.com/etherealxx/batchlinks-webui/main/notification.mp3 -P /content/volatile-concentration-localux

!python launch.py --listen --xformers --enable-insecure-extension-access --theme dark --gradio-queue --multiple
```
